name: iOS CI with Tuist

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.1
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Verify Xcode version
        run: xcodebuild -version

      - name: Generate project with Tuist
        uses: tuist/tuist-action@0.13.0
        with:
          command: generate
          # arguments: '--force'  # Раскомментируйте, если нужно принудительно перегенерировать

      - name: Build
        run: |
          xcodebuild clean build \
            -workspace VK.xcworkspace \
            -scheme VK \
            -sdk iphoneos \
            -configuration Debug \
            -derivedDataPath DerivedData \
            CODE_SIGNING_ALLOWED=NO

      # Раскомментируйте, когда будете готовы запускать тесты
      # - name: Run tests
      #   run: |
      #     xcodebuild test \
      #       -workspace VK.xcworkspace \
      #       -scheme VK \
      #       -sdk iphonesimulator \
      #       -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.1' \
      #       -configuration Debug \
      #       -derivedDataPath DerivedData \
      #       CODE_SIGNING_ALLOWED=NO
