name: iOS CI with Tuist

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.1
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Verify Xcode version
        run: xcodebuild -version

      - name: Install Tuist
        uses: tuist/actions/install-tuist@v2
        
      - name: Generate project with Tuist (like make open)
        run: |
          rm -rf VK.xcworkspace VK.xcodeproj DerivedData
          tuist generate

      - name: Build
        run: |
          xcodebuild clean build \
            -workspace VK.xcworkspace \ 
            -scheme VK \  # Укажите вашу схему (из Tuist)
            -sdk iphoneos \
            -configuration Debug \
            -derivedDataPath DerivedData \
            CODE_SIGNING_ALLOWED=NO

#      - name: Run tests
#        run: |
#          xcodebuild test \
#            -workspace VK.xcworkspace \
#            -scheme VK \  # Схема с тестами
#            -sdk iphonesimulator \
#            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.1' \  # Адаптируйте под iOS 18 для Xcode 16.1
#            -configuration Debug \
#            -derivedDataPath DerivedData \
#            CODE_SIGNING_ALLOWED=NO
